services:
  - type: web
    name: flask-story-api
    env: python
    rootDir: backend  # This is key!
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    healthCheckPath: /health
